import {
  faArrowRight,
  faArrowRightToBracket,
  faBell,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCompass,
  faEnvelope,
  faEye,
  faEyeSlash,
  faLock,
  faMagnifyingGlass,
  faPenToSquare,
  faRightFromBracket,
  faShield,
  faFileContract,
  faTriangleExclamation,
  faUserCheck,
  faUsers,
  faUserSlash
} from '@fortawesome/free-solid-svg-icons';

export const APP_ICONS = {
  login: faArrowRightToBracket,
  arrowRight: faArrowRight,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  chevronDown: faChevronDown,
  explore: faCompass,
  contact: faEnvelope,
  email: faEnvelope,
  password: faLock,
  eye: faEye,
  eyeSlash: faEyeSlash,
  logout: faRightFromBracket,
  shield: faShield,
  contract: faFileContract,
  users: faUsers,
  search: faMagnifyingGlass,
  bell: faBell,
  alertFlag: faTriangleExclamation,
  edit: faPenToSquare,
  userSlash: faUserSlash,
  userCheck: faUserCheck
} as const;